name: CI

on:
  push:
    branches: ['**']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build Frontend
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js environment version 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Set environment variables
        run: |
          echo "NEXT_PUBLIC_MAPBOX_API_KEY=${{ secrets.NEXT_PUBLIC_MAPBOX_API_KEY }}" >> apps/frontend/.env
          echo "NEXT_PUBLIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PROJECT_ID }}" >> apps/frontend/.env

      - name: Build
        run: pnpm build
        working-directory: apps/frontend